### ISSUE TITLE
Training On Camera Data

### ISSUE THREAD

**Issue by nmharmon8** [uzh-rpg/agile_flight#54]
Hey,

While using the vision env, if I call ```getImage``` it returns an array of zeros. After reading through the flightmare documentation, it seems this is because the vision env dose not actually setup Unity? 

```c++
setUnity(unity_render_);
connectUnity();
updateUnity(frame_id);
```

Dose this seem correct? If so then is there a way to train a server with no display? My GPU box is a remote box and I can't forward the Unity GUI. Is there a headless mode to Unit that I am missing?

**Comment by yun-long** [comment]
make sure that the unity render is on and RGB camera is yes in the config file 

[config.yaml[(https://github.com/uzh-rpg/flightmare/blob/092ff357139b2e98fc92bcdee50f38f85b55246d/flightpy/configs/vision/config.yaml#L22-L36)

**Comment by nmharmon8** [comment]
I believe I have those values set correctly.

```yaml
rgb_camera:
  on: yes 
  t_BC: [0.0, 0.0, 0.3] # translational vector of the camera with repect to the body frame
  r_BC: [0.0, 0.0, -90] # rotational angle (roll, pitch, yaw) of the camera in degree.
  channels: 3
  width: 320 
  height: 240
  fov: 70.0
  enable_depth: yes 
  enable_segmentation: no
  enable_opticalflow: no

unity:
  scene_id: 0 # 0 warehouse, 1 street, 2 forest, 3 wasteland
  render: yes 
```

In the vision_env.cpp the render filed is read into ```unity_render_`
```c++
// environment
  if (cfg["unity"]) {
    unity_render_ = cfg["unity"]["render"].as<bool>();
    scene_id_ = cfg["unity"]["scene_id"].as<SceneID>();
  }
```

```unity_render``` is only used in the ```setUnity``` function. But ```setUnity``` is never called.
